variables:
  - name: nextest
    ask: Testing method
    select_in_values:
      - label: Standard
        value: false
      - label: Nextest <https://nexte.st/>
        value: true

ignores:
  - .git
