variables:
  - name: application
    ask: What is the kind of Rust project
    select_in_values:
      - label: Application
        value: true
      - label: Library
        value: false

  - name: nextest
    ask: Testing method
    default_value: true
    select_in_values:
      - label: Standard
        value: false
      - label: Nextest <https://nexte.st/>
        value: true

  - name: sort_dependencies
    ask: What is the kind of Rust project
    default_value: true
    select_in_values:
      - label: Yes
        value: true
      - label: No
        value: false

ignores:
  - .git

scripts:
  - message: "Installing Just"
    cmd: "cargo install just"
  - message: "Installing binstall"
    cmd: "cargo install binstall"
  - message: "Installing just requirement"
    cmd: "just requirements"